### ISSUE TITLE
Can you provide a sample behat.yml in the docs?

### ISSUE THREAD

**Issue by krewmarco** [tomav/docker-behat#4]
I'm new to Behat 3 and having trouble using this docker image.

Thanks

**Comment by richardtape** [comment]
Yeah I'd love to see an example behat.yml too. Any chance, @tomav ?

**Comment by tomav** [comment]
Sorry guys, I'm currently working on [another projet](https://github.com/tomav/docker-mailserver/tree/v2/) and won't have time to do anything here in the next weeks.

I'll be happy to merge is someone is motivated :-)

**Comment by Krzysiaczek** [comment]
Hi there 
I was able to make it up and running but I want to test the another docker running web application. 
I can't get any further with my tests than   
> ┌─@BeforeStep # FeatureContext::beforeStep()
>        │
>        ╳  Could not open connection (Behat\Mink\Exception\DriverException)

I am trying to link  both containers by adding additional options 
`docker run -t -i -h docker-behat --net=webnetwork --link web:web  -v $(pwd):/home/behat/data:rw tvial/behat /bin/zsh`
and it seems to work when I try to ping it from inside the docker-behat but I need to run ping as sudo user otherwise I got 

> ping: icmp open socket: Operation not permitted

Any clues how to fix it?

**Comment by tomav** [comment]
Hi @Krzysiaczek, I updated the project. This should help you: https://github.com/tomav/docker-behat/commit/c6aeafcc31e3ee0a1fb8aa3fd1dffa9c44c78f76
